theme = "catppuccin_mocha"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-inlay-hints = true
